config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # Home content controller
  post "change_home_content_line" => "home_content#change_home_content_line"
  get "home_content" => "home_content#get_home_content"

  # Link controller
  post "change_link_line" => "link#change_link_line"
  get "get_links" => "link#get_links"
  post "delete_link_line" => "link#delete_link_line"

  # Contact security controller
  post "change_contact_seg" => "security#change_contact_seg"
  post "delete_contact_seg" => "security#delete_contact_seg"
  get "get_contacts_seg" => "security#get_contacts_seg"

  # Offer controller
  get "get_offer" => "offer#get_offer"
  post "change_offer_line" => "offer#change_offer_line"
  post "delete_offer_line" => "offer#delete_offer_line"

  # Other controller
  post "save_contacts" => "other#save_contacts"
  get "get_contacts" => "other#get_contacts"


  # Client controller
  # post "new_user" => "client#new_user"
  # post "login_user" => "client#login_user"
  # post "check_user" => "client#check_user"
  post "recovery_password" => "client#recovery_password"
  get "new_user_password/:recovery_token" => "client#new_user_password", as: "new_user_password"
  post "change_user_password/:recovery_token" => "client#change_user_password"
  post "new_user_from_be" => "client#new_user_from_be"
  post "delete_user_from_be" => "client#delete_user_from_be"
  post "login_user_mongo" => "client#login_user_mongo"
  post "check_user_mongo" => "client#check_user_mongo"
  post "change_password_first_time" => "client#change_password_first_time"
  post "data_to_datatable" => "client#data_to_datatable"
  
  post "matricula_by_dni" => "home#matricula_by_dni"
  post "policies_by_dni" => "home#policies_by_dni"
  post "send_question" => "home#send_question"  

  # Admin controller Login
  get "sign_in" => "home#sign_in_template"
  get "sign_out_admin" => "home#sign_out_admin"
  post "sign_in_admin" => "home#sign_in_admin"
  post "create_user_admin" => "home#create_user_admin"

  # Post Match
  # match 'new_user' => "home#handle_options", via: :options
  # match 'login_user' => "home#handle_options", via: :options
  # match 'check_user' => "home#handle_options", via: :options
  match 'recovery_password' => "home#handle_options", via: :options
  match 'new_user_from_be' => "home#handle_options", via: :options
  match 'delete_user_from_be' => "home#handle_options", via: :options
  match 'login_user_mongo' => "home#handle_options", via: :options
  match 'check_user_mongo' => "home#handle_options", via: :options
  match 'matricula_by_dni' => "home#handle_options", via: :options
  match 'policies_by_dni' => "home#handle_options", via: :options
  match 'send_question' => "home#handle_options", via: :options
  match 'change_password_first_time' => "home#handle_options", via: :options
  match 'sign_in_admin' => "home#handle_options", via: :options
  match 'create_user_admin' => "home#handle_options", via: :options


  # get 'show_create_and_send_email' => "client#show_create_and_send_email"

  post 'schedule_cron_daily' => 'scheduler#schedule_cron_daily'
  get 'schedule_daily_execute_now' => 'scheduler#schedule_daily_execute_now'
  get 'unschedule_cron_daily' => 'scheduler#unschedule_cron_daily'
  get 'check_schedule' => 'scheduler#check_schedule'
  
  post 'schedule_cron_import' => 'scheduler#schedule_cron_import'
  get 'schedule_import_execute_now' => 'scheduler#schedule_import_execute_now'
  get 'unschedule_cron_import' => 'scheduler#unschedule_cron_import'
  get 'check_schedule_import' => 'scheduler#check_schedule'

  post 'import_clients' => 'client#import_xls'
end

app/models/home.rb
class Home
  include Mongoid::Document
  store_in collection: "home"

  field :name_id
  field :display_name
  field :active
end

app/controllers/home_controller.rb
require 'sendgrid-ruby'
# require 'securerandom'
# require 'fileutils'

# require 'savon'
# require 'fcm'

class HomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :require_login, only: [:index]

  def index    
    @home_content = Home.all.sort( { _id: 1 } )
    @links = Link.all.sort( { _id: 1 } )
    @contact_segs = Segur.all

    other_data = Other.all
    @other = {}
    Other.all.each do |item|
      @other[item.name] = item.data
    end

    @segur_type = SegurType.all

    @users = Client.all.sort( { _id: -1 } )
    @offer = Offer.all.sort( { _id: -1 } )

    @schedule_daily = Scheduler.where(type: "daily").first
    @schedule_import = Scheduler.where(type: "import").first
  end

  # OPTIONS handle_options
  def handle_options
    logger.debug "handle_options"
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'POST,OPTIONS,GET'
    response.headers['Access-Control-Allow-Headers'] = 'Content-Type,ACCESS_TOKEN'
    head :ok, content_type: "text/html"
  end

  def matricula_by_dni
    result = {}
    client = Client.where(dni: params[:dni].downcase).first
    other = Other.where(name: "auto_type").first

    matriculas = []
    if(client)

      matricula = {}
      client.policy.each do |policy|
        if(policy[:active] && policy[:type] == "auto")
          matricula[:company] = policy[:company]
          matricula[:matricula] = policy[:matricula]
          other.data.each do |type|
            if(policy[:auto_type] == type["name_id"])
              matricula[:auto_type] = type["name"]
            end
          end

          matriculas.push(matricula)
          matricula = {}
        end
      end

      result_data = {}

      result[:code] = 200
      result_data[:matriculas] = matriculas
      result[:data] = result_data
    else
      result[:code] = 400
    end

    response.headers['Access-Control-Allow-Origin'] = '*'
    render json: result
  end

  def policies_by_dni
    client = Client.where(dni: params[:dni].downcase).first

    result = {}
    policies = []
    if(client)
      client.policy.each do |policy|
        if(policy[:active])
          policies.push(policy)
        end
      end

      result_data = {}

      result[:code] = 200
      result_data[:policies] = policies
      result[:data] = result_data
    else
      result[:code] = 400
    end

    response.headers['Access-Control-Allow-Origin'] = '*'
    render json: result
  end

  def send_question
    other = Other.where(name: "question_mail").first

    @dni = params[:dni]
    @message = params[:message]

    result_response = {}
    if(send_question_mail(other.data))
      result_response[:code] = 200
      result_response[:text] = "success"
    else
      result_response[:code] = 400
      result_response[:text] = "error"
    end

    response.headers['Access-Control-Allow-Origin'] = '*'
    render json: result_response
  end

  def send_question_mail(questions_email)
    result = false
    begin
      from = SendGrid::Email.new(email: "question@eisenar.com")
      to = SendGrid::Email.new(email: questions_email)
      subject = "Contacto del usuario"
      data = render_to_string(template: "home/mail/from_question", layout: false)
      content = SendGrid::Content.new(type: 'text/html', value: data)
      mail = SendGrid::Mail.new(from, subject, to, content)
      sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
      response = sg.client.mail._('send').post(request_body: mail.to_json)

      result = true
    rescue Exception => e
      puts "Error message: #{e}"
    end

    return result
  end

  def hash_password(password)
    BCrypt::Password.create(password).to_s
  end
  
  def test_password(password, hash)
    BCrypt::Password.new(hash) == password
  end

  def sign_in_template
    if(session[:user_id_token])
      begin
        User.find(session[:user_id_token])
        redirect_to "/"
      rescue Mongoid::Errors::DocumentNotFound
        puts "User nao existe"
        render "home/sign_in", layout: "application"
      end
    else
      render "home/sign_in", layout: "application"
    end
  end

  def create_user_admin
    user = User.create()
    user.username = params[:username].downcase
    user.password = hash_password(params[:password])

    user.save
  end

  def sign_in_admin
    user = User.where(username: params[:username].downcase).first

    result_response = {}
    if(user && test_password(params[:password], user.password))
      session.clear
      session[:user_id_token] = user.id.as_json
      result_response[:code] = 200
      result_response[:text] = "success"
    else
      result_response[:code] = 400
      result_response[:text] = "error"
    end

    response.headers['Access-Control-Allow-Origin'] = '*'
    render json: result_response
  end

  def sign_out_admin
    session.clear
    redirect_to '/sign_in'
  end
  
  private

  def require_login
    if(session[:user_id_token])
      begin
        User.find(session[:user_id_token])
      rescue Mongoid::Errors::DocumentNotFound
        puts "User nao existe"
        redirect_to "/sign_in"
      end
    else
      redirect_to "/sign_in"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/content/_content.html.haml
.content-wrapper
  .container-fluid
    / Breadcrumbs
    %ol.breadcrumb
      %li.breadcrumb-item
        %a{href: "#"} Dashboard
      %li.breadcrumb-item.active.breadcrumb_personal Clientes
    / Content data
    = render partial: "home/content/data_links"
    = render partial: "home/content/data_contact"
    = render partial: "home/content/data_contact_seg"
    = render partial: "home/content/data_home"
    = render partial: "home/content/data_client"
    = render partial: "home/content/data_offer"
    = render partial: "home/content/data_config"
    #showtoast Guardado con éxito...
    #showtoast_offer Formatos aceptables: PDF, JPG, JPEG, PNG
    #showtoast_error Error al escribir en la base de datos

  %footer.sticky-footer
    .container
      .text-center
        %small Copyright © Eisenar 2018

app/views/home/content/_data_client.html.haml
.card.mb-3.data_client.content_area
  .card-header
    %i.fa.fa-area-chart
    .card-body
      %button.client_new.btn.btn-success.btn-rounded.btn-sm.my-0.float-right.mb-3{type: "button", 'data-toggle': "modal", 'data-target': "#client_modal", 'data-policy_data': [{}]} Añadir cliente
      %table#client_table_datatable.display{style: "width:100%"}
        %thead
          %tr
            %th Nombre
            %th Dni
            %th Telefono
            %th Mail
            %th Direction
            %th Editar
  .card-footer.small.text-muted

/ Modal
#client_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#myModalLabel.modal-title Cliente
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .form-group.row
          %label.col-sm-3.col-form-label{for: "colFormLabelClient1"} Nombre
          .col-sm-9
            %input#colFormLabelClient1.client_name.form-control{type: "text"}/
        .form-group.row
          %label.col-sm-3.col-form-label{for: "colFormLabelClient2"} Dni
          .col-sm-9
            %input#colFormLabelClient2.client_dni.form-control{type: "text"}/
        .form-group.row
          %label.col-sm-3.col-form-label{for: "colFormLabelClient3"} Telefono
          .col-sm-9
            %input#colFormLabelClient3.client_phone.form-control{type: "text"}/
        .form-group.row
          %label.col-sm-3.col-form-label{for: "colFormLabelClient4"} Email
          .col-sm-9
            %input#colFormLabelClient4.client_email.form-control{type: "text"}/
        .form-group.row
          %label.col-sm-3.col-form-label{for: "colFormLabelClient5"} Direction
          .col-sm-9
            %input#colFormLabelClient5.client_address.form-control{type: "text"}/
        %hr
        %h6 Polizas
        .policy_block_blank.hidden
          .form-group.row
            %label.col-sm-3.col-form-label{for: "colFormLabelClient10"} Active
            .col-sm-9
              %input.client_active{type:"checkbox", name:"active", checked: true}
          .form-group.row
            %label.col-sm-3.col-form-label{for: "colFormLabelClient6"} Compañia
            .col-sm-9
              %select.soflow.company_select
                %option{value: "none"}
                - @contact_segs.each_with_index do |line, index|
                  %option{value: line[:name_id], text: line[:name]}= line[:name]
          .form-group.row
            %label.col-sm-3.col-form-label{for: "colFormLabelClient7"} Ramo
            .col-sm-9
              %select.soflow.type_select
                %option{value: "none"}
                - @segur_type.each_with_index do |line, index|
                  %option{value: line.name, text: t("seguro.#{line.name}.name")}= t("seguro.#{line.name}.name")
          .form-group.row.hidden.matricula.sub_type
            -# %label.label_subtype.col-sm-3.col-form-label{for: "colFormLabelClient8"} Auto tipo
            %label.label_subtype.col-sm-3.col-form-label{for: "colFormLabelClient8"} Subtipo
            .col-sm-9
              - @segur_type.each_with_index do |line, index|
                -if(line.sub_type != nil)
                  %select.soflow.auto_type_select.sub_type_select.hidden{class: "type_#{line.name}"}
                    %option{value: "none"}
                    - line.sub_type.each_with_index do |line_2, index_2|
                      %option{value: line_2["name"]}= t("seguro.#{line.name}.sub_type.#{line_2["name"]}")


          .form-group.row.hidden.matricula.extra_field
            - @segur_type.each_with_index do |line, index|
              -if(line.extra_field != nil)
                %label.col-sm-3.col-form-label.extra_field_select{for: "colFormLabelClient9", class: "type_#{line.name}"}= t("seguro.#{line.name}.extra_field.#{line.extra_field[0]}")
                .col-sm-9.extra_field_select{class: "type_#{line.name}"}
                  %input#colFormLabelClient8.client_matricula.extra_field_select.form-control{type: "text", class: "type_#{line.name}"}/
          .form-group.row.file
            %label.col-sm-3.col-form-label{for: "colFormLabelClient10"} Pdf
            .col-sm-9
              %a{ href: "", title: "PDF Document", target: "_blank" }
              %input{name: "file", type: "file", accept:"application/pdf"}/
          %button.btn.btn-danger.remove_poliza{type: "button"} Eliminar poliza
          %hr
        %button.btn.btn-success.add_poliza.float-right{type: "button"} Añadir poliza

      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Cerrar
        %button.btn.btn-primary.save{type: "button"} Guardar

app/views/home/content/_data_config.html.haml
.accordion.hidden.data_config.content_area
  .card
    #headingOne.card-header
      %h5.mb-0
        %button.btn.btn-link{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-target" => "#collapseOne", "data-toggle" => "collapse", type: "button"}
          Ciclo diario de los datos actualizados
    #collapseOne.collapse.show{"aria-labelledby" => "headingOne"}
      .card-body
        .form-row
          .form-group.col-md-1
            %label{for: "inputHour"} Hora
            %select#inputHour.inputHour.form-control.to_i
              - hour = @schedule_daily.original_hour
              - ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"].each do |value|
                - if(value == hour)
                  %option{selected: "selected"}= value
                - else
                  %option= value
          .form-group.col-md-1
            %label{for: "inputMinute"} Minute
            %select#inputMinute.inputMinute.form-control
              - minute = @schedule_daily.cron_time.split(" ")[0]
              - ["00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"].each do |value|
                - if(value == minute)
                  %option{selected: "selected"}= value
                - else
                  %option= value
        .form-group
          .form-check
            %input#activeExecute1.activeExecute1.form-check-input{type: "checkbox", checked: @schedule_daily.active }/
            %label.form-check-label{for: "activeExecute1"}
              Activado
        %button.btn.btn-primary.save_cron_execute_1{type: "submit"} Guardar
        %hr
          %button.btn.btn-danger{type: "submit", "data-toggle": "modal", "data-target": "#confirmExecute1"} Ejecutar ahora

  .card
    #headingTwo.card-header
      %h5.mb-0
        %button.btn.btn-link{"aria-controls" => "collapseTwo", "aria-expanded" => "false", "data-target" => "#collapseTwo", "data-toggle" => "collapse", type: "button"}
          Ciclo de importación de datos de la API
    #collapseTwo.collapse.show{"aria-labelledby" => "headingTwo"}
      .card-body
        .form-row
          .form-group.col-md-1
            %label{for: "inputHour"} Hora
            %select#inputHour.inputHour.form-control.to_i
              - hour = @schedule_import.original_hour
              - ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"].each do |value|
                - if(value == hour)
                  %option{selected: "selected"}= value
                - else
                  %option= value
          .form-group.col-md-1
            %label{for: "inputMinute"} Minute
            %select#inputMinute.inputMinute.form-control
              - minute = @schedule_import.cron_time.split(" ")[0]
              - ["00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55"].each do |value|
                - if(value == minute)
                  %option{selected: "selected"}= value
                - else
                  %option= value
        .form-group
          .form-check
            %input#activeExecute1.activeExecute1.form-check-input{type: "checkbox", checked: @schedule_import.active }/
            %label.form-check-label{for: "activeExecute1"}
              Activado
        %button.btn.btn-primary.save_cron_execute_2{type: "submit"} Guardar
        %hr
          %button.btn.btn-danger{type: "submit", "data-toggle": "modal", "data-target": "#confirmExecute2"} Ejecutar ahora
  .card
    #headingThree.card-header
      %h5.mb-0
        %button.btn.btn-link{"aria-controls" => "collapseThree", "aria-expanded" => "false", "data-target" => "#collapseThree", "data-toggle" => "collapse", type: "button"}
          Import xls
    #collapseThree.collapse.show{"aria-labelledby" => "headingThree"}
      .card-body
        .import_info
          %h2 Import clientes
          = form_tag import_clients_path, multipart: true do
            = file_field_tag :file
            = submit_tag "Import"

#confirmExecute1.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Confirmar la ejecución
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        De seguro que desea ejecutar ahora, antes de ciclo predeterminado
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Cerrar
        %button.save_cron_execute_1_now.btn.btn-primary{type: "button"} Ejecutar

#confirmExecute2.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Confirmar la ejecución
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        De seguro que desea ejecutar ahora, antes de ciclo predeterminado
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Cerrar
        %button.save_cron_execute_2_now.btn.btn-primary{type: "button"} Ejecutar

app/views/home/content/_data_contact.html.haml
.card.mb-3.hidden.contact_data.content_area
  .card-header
    %i.fa.fa-area-chart
    Contact
  .card-body
    .form-group.row
      %label.col-sm-3.col-form-label{for: "colFormLabel1"} Contactos en Sevilla
      .col-sm-9
        %textarea.form-control#colFormLabel1.contact_map_sevilla{rows: 4}= @other["contact_sevilla"].join("\n\r")
    .form-group.row
      %label.col-sm-3.col-form-label{for: "colFormLabel2"} Contactos en Madrid
      .col-sm-9
        %textarea.form-control#colFormLabel2.contact_map_madrid{rows: 4}= @other["contact_madrid"].join("\n\r")
    .form-group.row
      %label.col-sm-3.col-form-label{for: "colFormLabel3"} Contactos interes
      .col-sm-9
        %textarea.form-control#colFormLabel3.contact_map_interes{rows: 4}= @other["contact_interes"].join("\n\r")
    .form-group.row
      %label.col-sm-3.col-form-label{for: "colFormLabel4"} Question email
      .col-sm-9
        %input#colFormLabel4.form-control.questions_email{type: "text", value: "#{ @other["question_mail"] }"}/
    .form-group.row
      %label.col-sm-3.col-form-label{for: "colFormLabel5"} Contacto oferta
      .col-sm-9
        %input#colFormLabel5.form-control.offer_contact{type: "text", value: "#{ @other["offer_contact"] }"}/

    %button.btn.btn-primary.btn-rounded.btn-sm.my-0#save_data_contact{type: "button"} Guardar
  .card-footer.small.text-muted

app/views/home/content/_data_contact_seg.html.haml
.card.mb-3.hidden.contact_seg_data.content_area
  .card-header
    %i.fa.fa-area-chart
    Insurance contact
  .card-body
    %button.btn.btn-success.btn-rounded.btn-sm.my-0#seg_add_line.float-right.mb-3{type: "button"} Añadir seguradora
    #table.table-editable
      %span.table-add.float-right.mb-3.mr-2
        %a.text-success{href: "#!"}
          %i.fa.fa-plus.fa-2x{"aria-hidden" => "true"}
      %table.table.table-bordered.table-responsive-md.table-striped.text-center.seg_table
        %tr
          %th.text-center Logo nuevo
          %th.text-center Logo preview
          %th.text-center Nombre
          %th.text-center Telefono
          %th.text-center Email
          %th.text-center Editar
        - @contact_segs.each_with_index do |line, index|
          %tr.contact_seg_tr
            %td.td_link.pt-3-half{contenteditable: "false", style: "width: 100px;"}
              %input{name: "file", type: "file", accept: "image/*"}/
            %td.preview_td.pt-3-half{contenteditable: "false"}
              %img{src: line[:link]}
            %td.td_name.pt-3-half{contenteditable: "true"}= line[:name]
            %td.td_phone.pt-3-half{contenteditable: "true"}= line[:phone]
            %td.td_email.pt-3-half{contenteditable: "true"}= line[:email]
            %td
              %span.table-edit
                %button.btn.btn-warning.btn-rounded.btn-sm.my-0.contact_seg_edit_button{type: "button", line_id: line.id.as_json} Editar
              %span.table-detele
                %button.btn.btn-danger.btn-rounded.btn-sm.my-0.contact_seg_delete_button{type: "button", line_id: line.id.as_json} Eliminar
  .card-footer.small.text-muted

app/views/home/content/_data_home.html.haml
.card.mb-3.hidden.home_data.content_area
  .card-header
    %i.fa.fa-area-chart
    Home content
  .card-body
    #table.table-editable
      %span.table-add.float-right.mb-3.mr-2
        %a.text-success{href: "#!"}
          %i.fa.fa-plus.fa-2x{"aria-hidden" => "true"}
      %table.table.table-bordered.table-responsive-md.table-striped.text-center
        %tr
          %th.text-center Nombre original
          %th.text-center Nombre display
          %th.text-center Visible
          %th.text-center Editar
        - @home_content.each_with_index do |line, index|
          %tr.tr_home_content
            %td.td_name_id.pt-3-half{contenteditable: "false"}= line[:name_id]
            %td.td_display_name.pt-3-half{contenteditable: "true"}= line[:display_name]
            %td.td_active.pt-3-half
              %input{type: 'checkbox', checked: line[:active]}
            %td
              %span.table-edit
                %button.btn.btn-warning.btn-rounded.btn-sm.my-0.edit_button_home_content{type: "button", "data-line_id": line.id.as_json} Editar
  .card-footer.small.text-muted

app/views/home/content/_data_links.html.haml
.card.mb-3.hidden.links_data.content_area
  .card-header
    %i.fa.fa-area-chart
    Links and title
  .card-body
    %button.btn.btn-success.btn-rounded.btn-sm.my-0#link_add_line.float-right.mb-3{type: "button"} Añadir enlace
    #link_table.table-editable
      %span.table-add.float-right.mb-3.mr-2
        %a.text-success{href: "#!"}
          %i.fa.fa-plus.fa-2x{"aria-hidden" => "true"}
      %table.table.table-bordered.table-responsive-md.table-striped.text-center.link_table
        %tr
          %th.text-center Nombre
          %th.text-center Link
          %th.text-center Editar
        - @links.each_with_index do |line, index|
          %tr.link_add_content
            %td.name_td.pt-3-half{contenteditable: "true"}= line[:name]
            %td.url_td.pt-3-half{contenteditable: "true"}= line[:url]
            %td
              %span.table-edit
                %button.btn.btn-warning.btn-rounded.btn-sm.my-0.link_edit_button{type: "button", line_id: line.id.as_json} Editar
              %span.table-detele
                %button.btn.btn-danger.btn-rounded.btn-sm.my-0.link_delete_button{type: "button", line_id: line.id.as_json} Eliminar
      
  .card-footer.small.text-muted

app/views/home/content/_data_offer.html.haml
.card.mb-3.hidden.data_offer.content_area
  .card-header
    %i.fa.fa-area-chart
    Ofertas
  .card-body
    %button.btn.btn-success.btn-rounded.btn-sm.my-0#offer_add_line.float-right.mb-3{type: "button"} Añadir oferta
    #offer_table.table-editable
      %span.table-add.float-right.mb-3.mr-2
        %a.text-success{href: "#!"}
          %i.fa.fa-plus.fa-2x{"aria-hidden" => "true"}
      %table.table.table-bordered.table-responsive-md.table-striped.text-center.offer_table
        %tr
          %th.text-center Nombre
          %th.text-center Descripción
          %th.text-center Visible
          %th.text-center Preview
          %th.text-center Enlace
          %th.text-center Editar
        - @offer.each_with_index do |line, index|
          %tr.offer_add_content
            %td.name_td.pt-3-half{contenteditable: "true"}= line[:name]
            %td.description_td.pt-3-half{contenteditable: "true"}= line[:description]
            %td.visible_td.pt-3-half
              %input{type: 'checkbox', checked: line[:visible]}
            %td.preview_td.pt-3-half{contenteditable: "false"}
              - if (line[:type] != "application/pdf")
                %img{src: line[:file_info][:url]}
              -else
                %img{src: "pdf.png"}
            %td.link_td.pt-3-half{contenteditable: "false"}
              %input{name: "file", type: "file", accept: "image/jpeg,image/png,application/pdf"}/
            %td
              %span.table-edit
                %button.btn.btn-warning.btn-rounded.btn-sm.my-0.offer_edit_button{type: "button", line_id: line.id.as_json} Editar
              %span.table-detele
                %button.btn.btn-danger.btn-rounded.btn-sm.my-0.offer_delete_button{type: "button", line_id: line.id.as_json} Eliminar
        
  .card-footer.small.text-muted